---
title: "Base dos dados - Manual para o R"
author: "André Santos"
date: "12/10/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Importação dos dados

```{r, message=FALSE, warning=FALSE}
# install.packages("basedosdados")
library("basedosdados")
library(DBI)
library(bigrquery)
library(ggplot2)
```

## Definir seu projeto no Google Cloud

```{r, message=FALSE, warning=FALSE}
set_billing_id("<dadosrais-353316>")
```

## Criar arquivo de credenciais e salvar numa pasta
 https://console.cloud.google.com/apis/credentials/serviceaccountkey?project=<project_id>
 service account name: admin
 role: project owner

```{r, message=FALSE, warning=FALSE}
rm(list = ls())
bq_auth(path = "/Downloads/dadosrais-353316-d1e54f16f750.json")
```

## carregar dados no R

```{r, message=FALSE, warning=FALSE}
con <- dbConnect(
  bigrquery::bigquery(),
  billing = "dadosrais-353316",
  project = "basedosdados")
```

```{r, message=FALSE, warning=FALSE}
query = "SELECT * FROM `basedosdados.br_ms_sim.municipio`"

df= dbGetQuery(con, query)
```